### ISSUE TITLE
Workspaces

### ISSUE THREAD

**Issue by F4kund0** [okubax/dotfiles#2]
Hi mate. One question, how do you manage to get work your workspaces on i3? I’m facing that my workspace 3 shows as 4 and so on

**Comment by okubax** [comment]
I assume you're using the i3 config & bar in my repo, I have recently updated my i3/config, and so, I just use the default workspace numbering i.e 1,2,3,4 and then using the wmctrl program, lemonbar can show the workspace number I'm currently working in. 
NOTE: If you've assigned variables to your workspaces in your i3 config, it might create some issue with the config i'm using. For example, if you have similar lines in your i3config, it might not work with my lemonbar setup -

`set $WS1 I`
`bindsym $mod+1 workspace $WS1`
or
`bindsym $mod+Shift+1 move container to workspace $WS1`
